server {
    listen 80;
   server_name ec2-44-201-111-246.compute-1.amazonaws.com;

    # Serve os arquivos estáticos do React
    location / {
        root /home/ubuntu/Pizzaria_ecommerce/frontend/dist;
        index index.html;
        try_files $uri /index.html;
    }

    location /static/ {
        alias /home/ubuntu/Pizzaria_ecommerce/backend/staticfiles/;
    }

 # Encaminha rotas de autenticação para o backend Django
    location /auth/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;       
        proxy_set_header X-Forwarded-Proto $scheme;
    }

  # Encaminha chamadas para API (Django)
    location /api/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }


    # Django Admin
    location /admin/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
