upstream backend_server {
    server 127.0.0.1:8000;  # Django com Gunicorn rodando localmente
}

server {
    listen 80;
    server_name localhost;

    # Configuração para servir os arquivos estáticos do React (build)
    location / {
        root /usr/share/nginx/html;  # Diretório onde estará o build do React
        index index.html;
        try_files $uri $uri/ /index.html;  # Para o React Router funcionar
    }

    # Configuração para o Django/Gunicorn
    location /api/ {
        proxy_pass http://backend_server;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Configuração para o painel admin do Django
    location /admin/ {
        proxy_pass http://backend_server;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Configuração para arquivos estáticos do Django
    location /static/ {
        alias /app/backend/static/;  # Diretório dos arquivos estáticos do Django
    }

    # Configuração para arquivos de mídia do Django
    location /media/ {
        alias /app/backend/media/;   # Diretório dos arquivos de mídia do Django
    }
}
